### ISSUE TITLE
config.yaml missing

### ISSUE THREAD

**Issue by biobenkj** [caltech-bioinformatics-resource-center/Guttman_Ismagilov_Labs#2]
Congratulations on this amazing work! I'm trying to run the scSPRITE pipeline via snakemake and it appears the config.yaml is missing from the repo? Could you direct me to where this file lives or upload it?

Thanks again for providing code and congrats on scSPRITE!

**Comment by gaofan83** [comment]
Thanks. Just uploaded the config.yaml file.
