### ISSUE TITLE
python folder missing

### ISSUE THREAD

**Issue by seburgess** [caltech-bioinformatics-resource-center/Guttman_Ismagilov_Labs#3]
trying to run the snakemake pipeline it fails searching for the python directory in misc/sprite-pipeline/  

the "sprite-pipeline" github page (https://github.com/GuttmanLab/sprite-pipeline) has a python folder but it does not seem to contain all the needed files (e.g. "filter_all_tags.py")

**Comment by seburgess** [comment]
The R folder is missing as well.

**Comment by gaofan83** [comment]
Uploaded. Thanks.
